# Generated by Django 2.2.1 on 2019-05-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_point', models.TextField()),
                ('request', models.TextField()),
                ('response', models.TextField()),
            ],
        ),
    ]
